use std::collections::BTreeMap;

use crate::config::{Config, EvSource, EvType, NamespaceEntry};

fn insert_at_path<'src>(
	map: &mut BTreeMap<&'src str, NamespaceEntry<'src>>,
	path: &[&'src str],
	entry: NamespaceEntry<'src>,
) {
	assert!(!path.is_empty());
	let key = path[0];
	if path.len() == 1 {
		map.insert(key, entry);
	} else if let NamespaceEntry::Ns(sub_map) = map
		.entry(key)
		.or_insert_with(|| NamespaceEntry::Ns(BTreeMap::new()))
	{
		insert_at_path(sub_map, &path[1..], entry);
	}
}

/// Flattens the namespace tree into individual (path, entry) pairs for EvDecl/FnDecl leaves only.
pub fn collect_entries<'src>(config: &Config<'src>) -> Vec<(Vec<&'src str>, NamespaceEntry<'src>)> {
	let mut entries = Vec::new();
	config.visit_ns_entries(|path, entry| match entry {
		NamespaceEntry::EvDecl(_) | NamespaceEntry::FnDecl(_) => {
			entries.push((path.to_vec(), entry.clone()));
		}
		NamespaceEntry::Ns(_) => {}
	});
	entries
}

fn renumber_entries<'src>(
	mut entries: Vec<(Vec<&'src str>, NamespaceEntry<'src>)>,
) -> Vec<(Vec<&'src str>, NamespaceEntry<'src>)> {
	let mut server_reliable_id = 0usize;
	let mut server_unreliable_id = 0usize;
	let mut client_reliable_id = 0usize;
	let mut client_unreliable_id = 0usize;

	for (_, entry) in &mut entries {
		match entry {
			NamespaceEntry::EvDecl(ev) => {
				let new_id = match (ev.from, ev.evty) {
					(EvSource::Client, EvType::Reliable) => {
						let id = server_reliable_id;
						server_reliable_id += 1;
						id
					}
					(EvSource::Client, EvType::Unreliable(_)) => {
						let id = server_unreliable_id;
						server_unreliable_id += 1;
						id
					}
					(EvSource::Server, EvType::Reliable) => {
						let id = client_reliable_id;
						client_reliable_id += 1;
						id
					}
					(EvSource::Server, EvType::Unreliable(_)) => {
						let id = client_unreliable_id;
						client_unreliable_id += 1;
						id
					}
				};
				ev.id = new_id;
			}
			NamespaceEntry::FnDecl(f) => {
				f.server_id = server_reliable_id;
				f.client_id = client_reliable_id;
				server_reliable_id += 1;
				client_reliable_id += 1;
			}
			NamespaceEntry::Ns(_) => {}
		}
	}

	entries
}

/// Creates a shard Config from a subset of entries with renumbered IDs.
pub fn make_shard_config<'src>(
	base: &Config<'src>,
	entries: Vec<(Vec<&'src str>, NamespaceEntry<'src>)>,
	shard_index: usize,
) -> Config<'src> {
	let renumbered = renumber_entries(entries);

	let mut namespaces = BTreeMap::new();
	for (path, entry) in renumbered {
		insert_at_path(&mut namespaces, &path, entry);
	}

	let mut shard = base.clone();
	shard.namespaces = namespaces;
	shard.remote_scope = format!("{}_{}", base.remote_scope, shard_index);
	shard.max_events_per_file = None;
	shard
}

/// Derives the file stem for shard N from a base output path.
/// "net/server.luau", 0  =>  "server_shard_0"
pub fn shard_stem(base_path: &str, index: usize) -> String {
	let stem = std::path::Path::new(base_path)
		.file_stem()
		.and_then(|s| s.to_str())
		.unwrap_or("output");
	format!("{}_shard_{}", stem, index)
}

/// Derives the full output path for shard N.
/// "net/server.luau", 0  =>  "net/server_shard_0.luau"
pub fn shard_path(base_path: &str, index: usize) -> String {
	let path = std::path::Path::new(base_path);
	let stem = shard_stem(base_path, index);
	let ext = path.extension().and_then(|e| e.to_str()).unwrap_or("lua");
	match path.parent().and_then(|p| p.to_str()) {
		Some(dir) if !dir.is_empty() => format!("{}/{}.{}", dir, stem, ext),
		_ => format!("{}.{}", stem, ext),
	}
}

/// Returns the Roblox script reference string for a shard from within the aggregator.
/// Uses `script.X` when the aggregator is `init.luau`, otherwise `script.Parent.X`.
fn shard_require_ref(base_path: &str, index: usize) -> String {
	let is_init = std::path::Path::new(base_path)
		.file_stem()
		.map(|s| s == "init")
		.unwrap_or(false);
	let stem = shard_stem(base_path, index);
	if is_init {
		format!("script.{stem}")
	} else {
		format!("script.Parent.{stem}")
	}
}

fn aggregator_code(scope_label: &str, base_path: &str, send_events: &str, num_shards: usize) -> String {
	let mut buf = String::new();

	buf.push_str("--!nocheck\n");
	buf.push_str("--!nolint\n");
	buf.push_str(&format!(
		"-- {scope_label} generated by Zap v{} (https://github.com/red-blox/zap) (aggregator)\n",
		env!("CARGO_PKG_VERSION")
	));
	buf.push_str("task.wait()\n\n");

	for i in 0..num_shards {
		let ref_path = shard_require_ref(base_path, i);
		buf.push_str(&format!("local shard_{i} = require({ref_path})\n"));
	}
	buf.push('\n');

	buf.push_str("local function deep_merge(target, source, skip_key)\n");
	buf.push_str("\tfor k, v in source do\n");
	buf.push_str("\t\tif k == skip_key then continue end\n");
	buf.push_str("\t\tif type(target[k]) == \"table\" and type(v) == \"table\" then\n");
	buf.push_str("\t\t\tdeep_merge(target[k], v, skip_key)\n");
	buf.push_str("\t\telse\n");
	buf.push_str("\t\t\ttarget[k] = v\n");
	buf.push_str("\t\tend\n");
	buf.push_str("\tend\n");
	buf.push_str("end\n\n");

	buf.push_str("local result = {}\n");
	for i in 0..num_shards {
		buf.push_str(&format!("deep_merge(result, shard_{i}, \"{send_events}\")\n"));
	}
	buf.push('\n');

	buf.push_str(&format!("result.{send_events} = function()\n"));
	for i in 0..num_shards {
		buf.push_str(&format!("\tshard_{i}.{send_events}()\n"));
	}
	buf.push_str("end\n\n");

	buf.push_str("return table.freeze(result)\n");

	buf
}

pub fn aggregator_server_code<'src>(config: &Config<'src>, num_shards: usize) -> String {
	let send_events = config.casing.with("SendEvents", "sendEvents", "send_events");
	aggregator_code("Server", config.server_output, send_events, num_shards)
}

pub fn aggregator_client_code<'src>(config: &Config<'src>, num_shards: usize) -> String {
	let send_events = config.casing.with("SendEvents", "sendEvents", "send_events");
	aggregator_code("Client", config.client_output, send_events, num_shards)
}
